### ISSUE TITLE
Cache not restoring when using a manifest list.

### ISSUE THREAD

**Issue by dansamsara** [buildkite-plugins/cache-buildkite-plugin#109]
### Expected Behavior:

The plugin should be able restore a file level cache if it matches the hash resulting from a manifest list. Note, when defining a manifest list, the cache save works fine.

### Actual Behavior:

The plugin fails to restore an existing file cache previously created by the same manifest list. Note, no useful message is reported in the logs. The only output is:

```
Running plugin cache pre-command hook
/var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-cache-buildkite-plugin-v1-5-2/hooks/pre-command
--
```

### Example config:
```yaml
plugins:
  - cache#v1.5.2:
      backend: s3
      manifest:
          - package.json
          - yarn.lock
      path: node_modules
      restore: file
      compression: tgz
```

### Implementation

I suspect the cache restore failure is related to #106 where one reference to `"$(plugin_read_config MANIFEST)"` was missed in the fix to use `plugin_read_list`. See https://github.com/buildkite-plugins/cache-buildkite-plugin/blob/master/hooks/pre-command#L34.
