### ISSUE TITLE
Permission denied when restoring cache with S3

### ISSUE THREAD

**Issue by geoffharcourt** [buildkite-plugins/cache-buildkite-plugin#32]
We're restoring files from an S3 cache with v0.3.2 and seeing this error when the cache has a hit and the restore is attempted:

```
Cache hit at file level, restoring /bundle...
--
  |  
  | [Errno 13] Permission denied: '/bundle'
```

Here's the relevant part of our setup:

```yaml
steps:
  - label: ":docker: :bundler: Bundler"
    key: docker-gem-build
    env:
      BUILDKIT_PROGRESS: plain
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
    plugins:
      - ecr#v2.6.0:
          login: true
          account_ids: <REDACTED>
          region: <REDACTED>
      - cache#v0.3.2:
          backend: s3
          manifest: Gemfile.lock
          path: /bundle
          restore: file
          save: file
      - docker#v5.6.0:
          image: <REDACTED>
          command: ["bin/ci/bundle_install"]
          mount-checkout: true
          env-propagation-list: BUNDLE_ENTERPRISE__CONTRIBSYS__COM
          volumes:
            - "/bundle:/bundle"
```
