### ISSUE TITLE
S3 backend fails with status 255 on Elastic CI Stack for AWS

### ISSUE THREAD

**Issue by uh-toby** [buildkite-plugins/cache-buildkite-plugin#50]
Hi team,

I've tried using the s3 backend on agents running in the Elastic CI Stack for AWS using this configuration:

```
steps:
  - label: 'test caching'
    command: echo "test caching"
    plugins:
      - cache#v0.5.0:
          backend: s3
          manifest: .buildkite/pipeline.yml
          path: .buildkite
          restore: file
          save: file
```

and am getting this error: `Error: The plugin cache post-command hook exited with status 255`.

Permission to interact with the S3 bucket are granted through the EC2 instance role. I think I've configured the `BUILDKITE_PLUGIN_S3_CACHE_BUCKET` environment variable correctly: I tested it with a step:

```
steps:
  - label: 'test s3'
    command: aws s3 sync log "s3://${BUILDKITE_PLUGIN_S3_CACHE_BUCKET}/log"
```

which completed successfully.
