### ISSUE TITLE
Getting a "Waiting for folder lock" 

### ISSUE THREAD

**Issue by alagos** [buildkite-plugins/cache-buildkite-plugin#54]
I'm trying to integrate this plugin to the building process in our company with the following:
```yaml
      - cache#v0.5.0:
          manifest: webapp/npm-shrinkwrap.json # this exists, I've tried anything else and I get a `No such file or directory` message.
          path: webapp/node_modules
          restore: file
          save: file
```  
then when the build starts, as part of the initial groups I can see this:
```
~~~ Running plugin cache post-checkout hook
[90m$[0m /var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-cache-buildkite-plugin-v0-5-0/hooks/post-checkout
Cache miss up to file-level, sorry
```
which I think is normal, because there's no cache created yet, but right after the last step, where the new image is pushed to aws, I got this new last step which makes the build to fail:

```
~~~ Running plugin cache post-command hook
[90m$[0m /var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-cache-buildkite-plugin-v0-5-0/hooks/post-command
Saving file-level cache of webapp/node_modules

Waiting for folder lock

Waiting for folder lock

Waiting for folder lock

Waiting for folder lock

Waiting for folder lock

[31mðŸš¨ Error: The plugin cache post-command hook exited with status 1[0m
```
not sure if it's involved, but we also use the docker-compose plugin, so we create a container with the web app built that is eventually pushed to aws, so maybe this plugin operates out of that context? Is there a way to make it work in such conditions?
