### ISSUE TITLE
Support saving multiple cache types in one plugin definition

### ISSUE THREAD

**Issue by askoufis** [buildkite-plugins/cache-buildkite-plugin#70]
## Use case

I've got a single build step that caches a path based off a manifest file. I want to restore the cache based off that manifest, but fall back to a pipeline-level cache.

Unless I've misunderstood some part of the docs, currently the only way to achieve this is to define two separate instances of the plugin. For example:

```yaml
steps:
  plugins:
    - cache#v1.0.1:
        manifest: some-file
        path: ./some/path
        restore: pipeline
        save: file
    - cache#v1.0.1:
        path: ./some/path
        save: pipeline
```

When using the `compression` option, the above config will compress the same file/folder twice, instead of just uploading differently-named copies of the same compressed file.

## Potential implementation

IMO a nice way to represent this would be to allow specifying an array of values to `save`. For example:

```yaml
steps:
  plugins:
    - cache#v1.0.1:
        manifest: some-file
        path: ./some/path
        restore: pipeline
        save:
          - file
          - pipeline
```

An alternative could be some kind of restore key, similar to what [the cache github action provides](https://github.com/actions/cache?tab=readme-ov-file#inputs), though I'm not sure if that would align with this plugin's current configuration API.
