### ISSUE TITLE
Skip upload if step fails

### ISSUE THREAD

**Issue by amancevice** [buildkite-plugins/cache-buildkite-plugin#80]
I'm seeing an issue where a step fails partway through but the cache still uploads. This means that the subsequent retry step declines to upload the cache because it already found one. I think the plugin should skip uploading if the step doesn't exit cleanly.

Example configuration:

```yaml
- cache#v1.1.0:
    backend: s3
    compression: tgz
    manifest: REVISION
    path: public/assets
    restore: file
    save: file
```
